# Generated by Django 3.2.4 on 2023-11-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_driver_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=200)),
                ('phone', models.CharField(default='111111', max_length=15, unique=True)),
                ('mail', models.EmailField(default='dev@gmail.com', max_length=254, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Transgender', 'Transgender')], max_length=20)),
                ('lisence_upload', models.FileField(blank=True, upload_to='files/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=200)),
                ('phone', models.CharField(default='111111', max_length=15, unique=True)),
                ('mail', models.EmailField(default='dev@gmail.com', max_length=254, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Transgender', 'Transgender')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
