# Generated by Django 5.0.3 on 2024-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_application', '0002_cab_driver_info_password_user_info_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab_driver_info',
            name='password',
            field=models.CharField(default='null'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='password',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
