# Generated by Django 5.0.3 on 2024-05-15 04:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_application', '0003_alter_cab_driver_info_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_info',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='user', max_length=200)),
                ('phone', models.CharField(default='111111', max_length=15, unique=True)),
                ('mail', models.EmailField(default='dev@gmail.com', max_length=254, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Transgender', 'Transgender')], max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(default='null', max_length=50)),
                ('current_loc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('driver_id', models.CharField(max_length=50)),
                ('average_rating', models.FloatField(default=0.0)),
                ('feedback', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride_booking',
            fields=[
                ('_idd', models.CharField(default='null', editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=50)),
                ('driver_id', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('destinantion', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=200)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('Upi', 'Upi'), ('Cash', 'Cash')], max_length=20)),
                ('payment_id', models.CharField(choices=[('Upi', 'Upi'), ('Cash', 'Cash')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Not_paid', 'Not Paid'), ('Pending', 'Pending'), ('Completed', 'Comleted')], max_length=20)),
                ('rating', models.IntegerField(blank=True, default=None, help_text='Rating from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='vehicle_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_number', models.CharField(max_length=50, unique=True)),
                ('cab_model', models.CharField(max_length=100)),
                ('cab_color', models.CharField(max_length=50)),
                ('cab_type', models.CharField(max_length=50)),
                ('cab_registration', models.CharField(max_length=50)),
                ('vehicle_no', models.CharField(max_length=50)),
                ('year', models.CharField(help_text='Year of manufacture', max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
        migrations.RemoveField(
            model_name='cab_driver_info',
            name='id',
        ),
        migrations.AddField(
            model_name='cab_driver_info',
            name='_id',
            field=models.CharField(default='null', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cab_driver_info',
            name='current_loc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_detail',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_application.cab_driver_info'),
        ),
    ]
