# Generated by Django 5.0.3 on 2024-05-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_application', '0004_customer_info_rating_ride_booking_vehicle_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab_driver_info',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='_idd',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
